name: Release macOS
on: workflow_dispatch

jobs:
  release-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
 
      - name: Install QT
        run: brew install qt@5

      - name: Make release
        id: run-macos-build
        run: |
          mkdir build
          cd build
          cmake \
            -DCMAKE_INSTALL_PREFIX="./../install" \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=11 \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_PREFIX_PATH="$(brew --prefix qt5)" ../src
          make -j package

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: SHShare.dmg
          path: install/pack/SHShare-0.0.1-Darwin.dmg